apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOnsidXNlcm5hbWUiOiJzZW50aWVudGxhYnNvbHV0aW9ucyIsInBhc3N3b3JkIjoiZGNrcl9wYXRfdWh0dENMZTgwYWhRSWFLMFpiSThKZUthRU5VIiwiZW1haWwiOiJzZW50aWVudGxhYnNvbHV0aW9uc0BnbWFpbC5jb20iLCJhdXRoIjoiYzJWdWRHbGxiblJzWVdKemIyeDFkR2x2Ym5NNlpHTnJjbDl3WVhSZmRXaDBkRU5NWlRnd1lXaFJTV0ZMTUZwaVNUaEtaVXRoUlU1ViJ9fX0=
kind: Secret
metadata:
  name: sample-docker-secret
type: kubernetes.io/dockerconfigjson
