apiVersion: v1
kind: Pod
metadata:
  name: hello-app 
spec:
  containers:
  - image: sentientlabsolutions/learning_private_repo:latest
    name: learning-repo-s27c5
    ports: 
    - containerPort: 3000
  imagePullSecrets:
  - name: sample-docker-secret
