apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-08-06T01:01:18Z"
  labels:
    app: sample
  name: sample
  namespace: default
  resourceVersion: "30795"
  uid: 34acf7cf-8180-4388-91ea-acb4877f94f9
spec:
  clusterIP: 10.96.181.60
  clusterIPs:
  - 10.96.181.60
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
