apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-34
  name: nginx-3
spec:
  containers:
  - image: nginx
    name: nginx-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
