apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-application
  name: deploy-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-application
  strategy: {}
  template:
    metadata:
      labels:
        app: deploy-application
    spec:
      containers:
      - image: sentientlabsolutions/learning_repo:latest
        name: learning-repo-s27c5
        ports: 
        - containerPort: 3000