apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy2
  name: deploy2
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30080
    name: http
  selector:
    app: deploy2
status:
  loadBalancer: {}
