apiVersion: v1
kind: Pod 

metadata:
  name: hello-pod 

spec:
  containers:
  - name: hello-container 
    image: sentientlabsolutions/hello-k8s:v1 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000