"""add_timestamps

Revision ID: 8602d21c8a09
Revises: c4c823974246
Create Date: 2026-08-01 17:46:53.535484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8602d21c8a09'
down_revision: Union[str, Sequence[str], None] = 'c4c823974246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tools', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('agent_tools', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('agents', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tools', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tools', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'updated_at')
    op.drop_column('tools', 'created_at')
    op.drop_column('agents', 'updated_at')
    op.drop_column('agents', 'created_at')
    op.drop_column('agent_tools', 'updated_at')
    op.drop_column('agent_tools', 'created_at')
    # ### end Alembic commands ###
