apiVersion: v1 
kind: Pod 
metadata:
  name: nginx
  labels:
    app: nginx 
spec:
  volumes:
    - name: nginx-storage
      emptyDir: {}
  containers:
  - name: nginx
    image: nginx:latest 
    volumeMounts:
    - name: nginx-storage
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 3000
    

